### ISSUE TITLE
Observe "close" event on connection

### ISSUE THREAD

**Issue by inexorabletash** [domenic/async-local-storage#14]
Implementations fire `"close"` against the connection when it must be closed abnormally, e.g. in response to the user clearing browsing data.

See https://w3c.github.io/IndexedDB/#closing-connection and search on "forced flag"

A storageArea should probably listen for this, null out the [[Connection]], and set [[ConnectionError]]. I don't think we make the error details available anywhere useful in this case, so a synthetic DOMException would need to be created.

**Comment by domenic** [comment]
It seems the design you're proposing would essentially lock you out of using async local storage once the user clears browsing data. Is that correct? That doesn't seem super-friendly...

It seems potentially better to try to reopen the database in this case (i.e., null out [[DatabasePromise]] so that future operations lazily open it). That seems more like how local storage would behave.

What do you think?

**Comment by inexorabletash** [comment]
SGTM.
